baseURL = "https://docs.bonnal.ch"
languageCode = "en-us"
title = "benou docs"

[outputs]
  home = ["HTML", "JSON"]

[outputFormats.JSON]
  baseName = "index"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true

[params]
  description = "Personal documentation and knowledge base"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


